
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
slow_motion=2
### func #################################
# Generated by Selenium IDE

#ch chrome
#ff firefoxfocuse
#
useragent = {
  "firefox_android": "Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0",
  "ch_s20": "Mozilla/5.0 (Linux; Android 10; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36",
  "ch_note10p": "Mozilla/5.0 (Linux; Android 9; SM-N976V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Mobile Safari/537.36",
  "ch_s10" : "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G977N Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36",
  "focus" : "Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.7.1 Chrome/75.0.3770.143 Mobile Safari/537.36",
  "ubuntu" : "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
  "win_chrome" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"

}


profile = webdriver.FirefoxProfile()
profile.set_preference("general.useragent.override", useragent["firefox_android"] )
driver = webdriver.Firefox(profile)
actions = webdriver.ActionChains(driver)

#driver = webdriver.Chrome()





def change_ip():
    driver.get("http://10.10.10.1/")
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "Frm_Username").click()
    driver.find_element(By.ID, "Frm_Username").send_keys("admin")
    driver.find_element(By.ID, "Frm_Password").send_keys("MST123456789")
    driver.find_element(By.ID, "Frm_Password").send_keys(Keys.ENTER)
    time.sleep(0.2*slow_motion)
    driver.switch_to.frame(1)
    time.sleep(0.2*slow_motion)
    driver.find_element(By.CSS_SELECTOR, "#mmNet > .menuPlusSymbol").click()
    driver.find_element(By.ID, "ssmETHWAN46Con").click()
    driver.find_element(By.ID, "ssmTTYWANCon").click()
    driver.find_element(By.ID, "ssmETHWAN46Con").click()
    driver.find_element(By.ID, "Frm_WANCName0").click()
    time.sleep(0.2*slow_motion)
    dropdown = driver.find_element(By.ID, "Frm_WANCName0")
    dropdown.find_element(By.XPATH, "//option[. = 'omci_ipv4_pppoe_1']").click()
    driver.find_element(By.ID, "Frm_IpMode").click()
    dropdown = driver.find_element(By.ID, "Frm_IpMode")
    dropdown.find_element(By.XPATH, "//option[. = 'IPv4']").click()
    driver.find_element(By.CSS_SELECTOR, "#Frm_IpMode > option:nth-child(1)").click()
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "Btn_DoEdit").click()
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "Btn_DoEdit").click()
    time.sleep(0.1*slow_motion)
    time.sleep(2*slow_motion)
    driver.find_element(By.ID, "Frm_IpMode").click()
    dropdown = driver.find_element(By.ID, "Frm_IpMode")
    dropdown.find_element(By.XPATH, "//option[. = 'IPv4/v6']").click()
    driver.find_element(By.CSS_SELECTOR, "#Frm_IpMode > option:nth-child(3)").click()
    driver.find_element(By.ID, "Frm_IsAuto").click()
    dropdown = driver.find_element(By.ID, "Frm_IsAuto")
    dropdown.find_element(By.XPATH, "//option[. = 'Auto Mode']").click()
    driver.find_element(By.CSS_SELECTOR, "#Frm_IsAuto > option:nth-child(2)").click()
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "Btn_DoEdit").click()
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "Btn_DoEdit").click()
    time.sleep(0.1*slow_motion)
    time.sleep(0.5*slow_motion)
    driver.find_element(By.ID, "Fnt_mmStatu").click()
    time.sleep(0.5*slow_motion)
    time.sleep(0.1*slow_motion)
 
def new_colab(user="assafi10003",passw="Ms123456789"):
    driver.get("https://accounts.google.com/signin/v2/identifier?authuser=0&hl=en&continue=https%3A%2F%2Fcolab.research.google.com%2F%23create%3Dtrue&flowName=GlifWebSignIn&flowEntry=ServiceLogin")
    driver.find_element(By.ID, "identifierId").send_keys(user)
    driver.find_element(By.ID, "identifierId").send_keys(Keys.ENTER)
    time.sleep(2*slow_motion)
    time.sleep(0.1*slow_motion)
    driver.find_element(By.NAME, "password").send_keys(passw)
    driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)  
    time.sleep(0.1*slow_motion)

def init_gpu():
    driver.find_element(By.CSS_SELECTOR, "#runtime-menu-button .goog-menu-button-caption").click()
    driver.find_element(By.CSS_SELECTOR, "#\\3A 26 > .goog-menuitem-content").click()
    element = driver.find_element(By.ID, "accelerator")
    actions.move_to_element(element).click_and_hold().perform()
    element = driver.find_element(By.ID, "accelerator")
    actions.move_to_element(element).perform()
    element = driver.find_element(By.ID, "accelerator")
    actions.move_to_element(element).release().perform()
    driver.find_element(By.ID, "accelerator").click()
    dropdown = self.driver.find_element(By.ID, "accelerator")
    dropdown.find_element(By.XPATH, "//option[. = 'GPU']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.ID, "ok").click()

def exec_colab():
  
time.sleep(0.1*slow_motion)
print(0.1*slow_motion)         
#driver.set_window_size(360, 667)
driver.get("about:blank")
driver.maximize_window() 
change_ip()
time.sleep(5*slow_motion)

driver.set_window_size(360, 667)
#driver.set_window_size(1366, 768)
#driver.get("https://www.whatismybrowser.com/fr/")
#driver.get("https://console.cloud.google.com/")
new_colab(user="assafi10002",passw="Ms123456789")
init_gpu()

action.key_down(Keys.SHIFT).send_keys_to_element(search, "qwerty").key_up(Keys.SHIFT).send_keys("qwerty").perform()

#driver.close()