#!/usr/bin/python
import shlex
import subprocess
from subprocess import Popen, PIPE
import pyautogui
import pytest
import time
import pty
import sys
import select
import os
import pytest
import time
import json
import sys
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
slow_motion = 1
slow_motion=1
### func #################################
# Generated by Selenium IDE

#ch chrome
#ff firefoxfocuse
#
#user_id=sys.argv[1]
#gpassword=sys.argv[2]


useragent = {
  "original_fi": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
  "original_ch": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "firefox_android": "Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0",
  "ch_s20": "Mozilla/5.0 (Linux; Android 10; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36",
  "ch_note10p": "Mozilla/5.0 (Linux; Android 9; SM-N976V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Mobile Safari/537.36",
  "ch_s10" : "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G977N Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36",
  "focus" : "Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.7.1 Chrome/75.0.3770.143 Mobile Safari/537.36",
  "ubuntu" : "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/88.0",
  "win_firefox" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0",
  "win_chrome" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "ff2mobile" : "Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"

}




#options = webdriver.ChromeOptions() 
#options.add_argument("start-maximized")
#options.add_argument("--disable-dev-shm-usage")
#options.add_argument('--disable-extensions')
#options.add_argument('--disable-blink-features')
#options.add_argument('--profile-directory=Default')
#options.add_argument("--incognito")
#options.add_argument("--disable-plugins-discovery");
#options.add_argument("--start-maximized")
#options.add_argument("--disable-blink-features=AutomationControlled")
#options.add_argument("--disable-infobars")
#options.add_argument("--remote-debugging-port=9222");
#options.add_experimental_option("excludeSwitches", ["enable-automation"])
#options.add_experimental_option('useAutomationExtension', False)
#driver = webdriver.Chrome(options=options)
# #### options.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE); #####
#driver.execute_cdp_cmd('Network.setUserAgentOverride', {"userAgent": useragent["original_ch"] })
#driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")




profile = webdriver.FirefoxProfile()
options = webdriver.FirefoxOptions()
options.add_argument("--headless")
profile.set_preference("dom.webdriver.enabled", False)
profile.set_preference('useAutomationExtension', False)
profile.set_preference("general.useragent.override", useragent["ff2mobile"] )
profile.update_preferences()
desired = DesiredCapabilities.FIREFOX

driver = webdriver.Firefox(firefox_profile=profile,options=options,
                           desired_capabilities=desired)


actions = webdriver.ActionChains(driver) 
print(driver.execute_script("return navigator.userAgent;"))

def newacc_step1():
    try:  
        #driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
        driver.set_window_size(360, 667)
        driver.get("https://console.cloud.google.com/")
        time.sleep(3*slow_motion)
        actions.key_down(Keys.TAB).key_up(Keys.TAB).perform()
        time.sleep(0.1*slow_motion)
        actions.key_down(Keys.TAB).key_up(Keys.TAB).perform()
        time.sleep(0.1*slow_motion)
        actions.key_down(Keys.TAB).key_up(Keys.TAB).perform()
        time.sleep(0.1*slow_motion)
        actions.key_down(Keys.TAB).key_up(Keys.TAB).perform()
        time.sleep(0.1*slow_motion)
        time.sleep(0.2*slow_motion)
        actions.key_down(Keys.ENTER).key_up(Keys.ENTER).perform()
        #actions.pause(1)
        #actions.key_down(Keys.ARROW_DOWN).key_up(Keys.ARROW_DOWN).perform()
        #time.sleep(0.1*slow_motion)
        #actions.key_down(Keys.ARROW_UP).key_up(Keys.ARROW_UP).perform()
        #time.sleep(0.1*slow_motion)
        #actions.key_down(Keys.ARROW_UP).key_up(Keys.ARROW_UP).perform()
        time.sleep(0.7*slow_motion)
        #actions.key_down(Keys.ENTER).key_up(Keys.ENTER).perform()    
        #driver.find_element(By.XPATH, "//div[6]/div/div").send_keys(Keys.ENTER)
        driver.find_element(By.XPATH, "//span[contains(.,'Pour moi')]").send_keys(Keys.ENTER)
        time.sleep(1*slow_motion)
        return "step 1 OK"
    except:
        print ("error step 1")
        return "step 1 OK"

def newacc_step2(firstName,lastName,username,password):
    time.sleep(2*slow_motion)
    driver.find_element(By.ID, "firstName").send_keys(firstName)
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "lastName").click()
    time.sleep(0.1*slow_motion)
    driver.find_element(By.ID, "lastName").send_keys(lastName)
    time.sleep(0.5*slow_motion)
    #actions.key_down(Keys.TAB).key_up(Keys.TAB).perform()
    #time.sleep(0.1*slow_motion)
    #actions.key_down(Keys.TAB).key_up(Keys.TAB).perform()
    #time.sleep(0.2*slow_motion)
    #actions.key_down(Keys.ENTER).key_up(Keys.ENTER).perform()
    #driver.find_element(By.XPATH, "//span[contains(.,'Cr�er une nouvelle adresse Gmail � la place')]").click()
    driver.find_element(By.XPATH, "//button/div[2]").click()
    time.sleep(0.7*slow_motion)
    driver.find_element(By.ID, "username").send_keys(username)
    time.sleep(0.1*slow_motion)
    driver.find_element(By.NAME, "Passwd").send_keys(password)
    time.sleep(0.1*slow_motion)
    driver.find_element(By.NAME, "ConfirmPasswd").send_keys(password)
    time.sleep(0.1*slow_motion)

    nextButton = driver.find_elements_by_xpath('//*[@id ="passwordNext"]')
    #nextButton[0].click()




def gauth(user,passw,authurl='https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com'):
    #driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
    driver.get(authurl)
    time.sleep(10*slow_motion)    
    driver.implicitly_wait(10)
    driver.find_element(By.ID, "identifierId").send_keys(user)
    driver.find_element(By.ID, "identifierId").send_keys(Keys.ENTER)
    time.sleep(3.6*slow_motion)
    driver.implicitly_wait(10)
    time.sleep(0.1*slow_motion)
    driver.find_element(By.NAME, "password").send_keys(passw)
    driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    driver.implicitly_wait(10)
    time.sleep(5*slow_motion) 

def accept_code(gurl):
    #driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
    driver.get(gurl)
    time.sleep(7*slow_motion)    
    driver.implicitly_wait(10)
    print('#########################')
    try:
        Acchoose=driver.find_element(By.CSS_SELECTOR, "ul li div div")
        print(Acchoose)
        Acchoose.click()
    finally:
        time.sleep(1.3*slow_motion)
        driver.implicitly_wait(10)
    driver.find_element(By.ID, "submit_approve_access").click()
    time.sleep(2.3*slow_motion)
    driver.implicitly_wait(10)
    KeyDriver=driver.find_element(By.CSS_SELECTOR, "textarea")
    print(KeyDriver.text)
    time.sleep(5*slow_motion)
    return KeyDriver.text



gaurl='https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=vOw8VugXaWq6nIloVLCQxIgUF5v8Xb&prompt=consent&access_type=offline&code_challenge=5X_NI6x8Bk173GnpvvwdPKJnokFpv6Ocf6RGx-ukjsA&code_challenge_method=S256'


def testo():
    time.sleep(0.1*slow_motion)
    print(0.1*slow_motion)         

    driver.get("about:blank")
    driver.maximize_window() 
    driver.set_window_size(360, 667)
    time.sleep(2*slow_motion)

gauth('siwar10001','Ms123456789')
accept_code(gaurl)